version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  front-end:
    container_name: front-end
    restart: always
    build: ./front-end
    ports:
      - "3000:3000"
    links:
      - app
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
